# -*- coding: utf-8 -*-
from django.utils.translation import ugettext as _
from django.db import models

#adapted from http://www.djangosnippets.org/snippets/494/
#using UN country and 3 char code list from http://unstats.un.org/unsd/methods/m49/m49alpha.htm
#correct as of 17th October 2008

COUNTRIES = (
    ('AFG', _('Afghanistan')), 
    ('ALA', _('Aland Islands')),
    ('ALB', _('Albania')),
    ('DZA', _('Algeria')),
    ('ASM', _('American Samoa')),
    ('AND', _('Andorra')),
    ('AGO', _('Angola')),
    ('AIA', _('Anguilla')),
    ('ATA', _('Antarctica')),
    ('ATG', _('Antigua and Barbuda')),
    ('ARG', _('Argentina')),
    ('ARM', _('Armenia')),
    ('ABW', _('Aruba')),
    ('AUS', _('Australia')),
    ('AUT', _('Austria')),
    ('AZE', _('Azerbaijan')),
    ('BHS', _('Bahamas')),
    ('BHR', _('Bahrain')),
    ('BGD', _('Bangladesh')),
    ('BRB', _('Barbados')),
    ('BLR', _('Belarus')),
    ('BEL', _('Belgium')),
    ('BLZ', _('Belize')),
    ('BEN', _('Benin')),
    ('BMU', _('Bermuda')),
    ('BTN', _('Bhutan')),
    ('BOL', _('Bolivia')),
    ('BIH', _('Bosnia and Herzegovina')),
    ('BWA', _('Botswana')),
    ('BRA', _('Brazil')),
    ('IOT', _('British Indian Ocean Territory')),
    ('VGB', _('British Virgin Islands')),
    ('BRN', _('Brunei Darussalam')),
    ('BGR', _('Bulgaria')),
    ('BFA', _('Burkina Faso')),
    ('BDI', _('Burundi')),
    ('KHM', _('Cambodia')),
    ('CMR', _('Cameroon')),
    ('CAN', _('Canada')),
    ('CPV', _('Cape Verde')),
    ('CYM', _('Cayman Islands')),
    ('CAF', _('Central African Republic')),
    ('TCD', _('Chad')),
    ('CIL', _('Channel Islands')),
    ('CHL', _('Chile')),
    ('CHN', _('China')),
    ('HKG', _('China - Hong Kong')),
    ('MAC', _('China - Macao')),
    ('CXR', _('Christmas Island')),
    ('CCK', _('Cocos (Keeling) Islands')),
    ('COL', _('Colombia')),
    ('COM', _('Comoros')),
    ('COG', _('Congo')),
    ('COK', _('Cook Islands')),
    ('CRI', _('Costa Rica')),
    ('CIV', _('Cote d\'Ivoire')),
    ('HRV', _('Croatia')),
    ('CUB', _('Cuba')),
    ('CYP', _('Cyprus')),
    ('CZE', _('Czech Republic')),
    ('PRK', _('Democratic People\'s Republic of Korea')),
    ('COD', _('Democratic Republic of the Congo')),
    ('DNK', _('Denmark')),
    ('DJI', _('Djibouti')),
    ('DMA', _('Dominica')),
    ('DOM', _('Dominican Republic')),
    ('ECU', _('Ecuador')),
    ('EGY', _('Egypt')),
    ('SLV', _('El Salvador')),
    ('GNQ', _('Equatorial Guinea')),
    ('ERI', _('Eritrea')),
    ('EST', _('Estonia')),
    ('ETH', _('Ethiopia')),
    ('FRO', _('Faeroe Islands')),
    ('FLK', _('Falkland Islands (Malvinas)')),
    ('FJI', _('Fiji')),
    ('FIN', _('Finland')),
    ('FRA', _('France')),
    ('GUF', _('French Guiana')),
    ('PYF', _('French Polynesia')),
    ('ATF', _('French Southern Territories')),
    ('GAB', _('Gabon')),
    ('GMB', _('Gambia')),
    ('GEO', _('Georgia')),
    ('DEU', _('Germany')),
    ('GHA', _('Ghana')),
    ('GIB', _('Gibraltar')),
    ('GRC', _('Greece')),
    ('GRL', _('Greenland')),
    ('GRD', _('Grenada')),
    ('GLP', _('Guadeloupe')),
    ('GUM', _('Guam')),
    ('GTM', _('Guatemala')),
    ('GGY', _('Guernsey')),
    ('GIN', _('Guinea')),
    ('GNB', _('Guinea-Bissau')),
    ('GUY', _('Guyana')),
    ('HTI', _('Haiti')),
    ('VAT', _('Holy See (Vatican City)')),
    ('HND', _('Honduras')),
    ('HUN', _('Hungary')),
    ('ISL', _('Iceland')),
    ('IND', _('India')),
    ('IDN', _('Indonesia')),
    ('IRN', _('Iran')),
    ('IRQ', _('Iraq')),
    ('IRL', _('Ireland')),
    ('IMN', _('Isle of Man')),
    ('ISR', _('Israel')),
    ('ITA', _('Italy')),
    ('JAM', _('Jamaica')),
    ('JPN', _('Japan')),
    ('JEY', _('Jersey')),
    ('JOR', _('Jordan')),
    ('KAZ', _('Kazakhstan')),
    ('KEN', _('Kenya')),
    ('KIR', _('Kiribati')),
    ('KWT', _('Kuwait')),
    ('KGZ', _('Kyrgyzstan')),
    ('LAO', _('Lao People\'s Democratic Republic')),
    ('LVA', _('Latvia')),
    ('LBN', _('Lebanon')),
    ('LSO', _('Lesotho')),
    ('LBR', _('Liberia')),
    ('LBY', _('Libyan Arab Jamahiriya')),
    ('LIE', _('Liechtenstein')),
    ('LTU', _('Lithuania')),
    ('LUX', _('Luxembourg')),
    ('MKD', _('Macedonia')),
    ('MDG', _('Madagascar')),
    ('MWI', _('Malawi')),
    ('MYS', _('Malaysia')),
    ('MDV', _('Maldives')),
    ('MLI', _('Mali')),
    ('MLT', _('Malta')),
    ('MHL', _('Marshall Islands')),
    ('MTQ', _('Martinique')),
    ('MRT', _('Mauritania')),
    ('MUS', _('Mauritius')),
    ('MYT', _('Mayotte')),
    ('MEX', _('Mexico')),
    ('FSM', _('Micronesia, Federated States of')),
    ('MCO', _('Monaco')),
    ('MNG', _('Mongolia')),
    ('MNE', _('Montenegro')),
    ('MSR', _('Montserrat')),
    ('MAR', _('Morocco')),
    ('MOZ', _('Mozambique')),
    ('MMR', _('Myanmar')),
    ('NAM', _('Namibia')),
    ('NRU', _('Nauru')),
    ('NPL', _('Nepal')),
    ('NLD', _('Netherlands')),
    ('ANT', _('Netherlands Antilles')),
    ('NCL', _('New Caledonia')),
    ('NZL', _('New Zealand')),
    ('NIC', _('Nicaragua')),
    ('NER', _('Niger')),
    ('NGA', _('Nigeria')),
    ('NIU', _('Niue')),
    ('NFK', _('Norfolk Island')),
    ('MNP', _('Northern Mariana Islands')),
    ('NOR', _('Norway')),
    ('PSE', _('Occupied Palestinian Territory')),
    ('OMN', _('Oman')),
    ('PAK', _('Pakistan')),
    ('PLW', _('Palau')),
    ('PAN', _('Panama')),
    ('PNG', _('Papua New Guinea')),
    ('PRY', _('Paraguay')),
    ('PER', _('Peru')),
    ('PHL', _('Philippines')),
    ('PCN', _('Pitcairn')),
    ('POL', _('Poland')),
    ('PRT', _('Portugal')),
    ('PRI', _('Puerto Rico')),
    ('QAT', _('Qatar')),
    ('KOR', _('Republic of Korea')),
    ('MDA', _('Republic of Moldova')),
    ('REU', _('Reunion')),
    ('ROU', _('Romania')),
    ('RUS', _('Russian Federation')),
    ('RWA', _('Rwanda')),
    ('BLM', _('Saint-Barthelemy')),
    ('SHN', _('Saint Helena')),
    ('KNA', _('Saint Kitts and Nevis')),
    ('LCA', _('Saint Lucia')),
    ('MAF', _('Saint-Martin (French part)')),
    ('SPM', _('Saint Pierre and Miquelon')),
    ('VCT', _('Saint Vincent and the Grenadines')),
    ('WSM', _('Samoa')),
    ('SMR', _('San Marino')),
    ('STP', _('Sao Tome and Principe')),
    ('SAU', _('Saudi Arabia')),
    ('SEN', _('Senegal')),
    ('SRB', _('Serbia')),
    ('SYC', _('Seychelles')),
    ('SLE', _('Sierra Leone')),
    ('SGP', _('Singapore')),
    ('SVK', _('Slovakia')),
    ('SVN', _('Slovenia')),
    ('SLB', _('Solomon Islands')),
    ('SOM', _('Somalia')),
    ('ZAF', _('South Africa')),
    ('ESP', _('Spain')),
    ('LKA', _('Sri Lanka')),
    ('SDN', _('Sudan')),
    ('SUR', _('Suriname')),
    ('SJM', _('Svalbard and Jan Mayen Islands')),
    ('SWZ', _('Swaziland')),
    ('SWE', _('Sweden')),
    ('CHE', _('Switzerland')),
    ('SYR', _('Syrian Arab Republic')),
    ('TWN', _('Taiwan')),
    ('TJK', _('Tajikistan')),
    ('THA', _('Thailand')),
    ('TLS', _('Timor-Leste')),
    ('TGO', _('Togo')),
    ('TKL', _('Tokelau')),
    ('TON', _('Tonga')),
    ('TTO', _('Trinidad and Tobago')),
    ('TUN', _('Tunisia')),
    ('TUR', _('Turkey')),
    ('TKM', _('Turkmenistan')),
    ('TCA', _('Turks and Caicos Islands')),
    ('TUV', _('Tuvalu')),
    ('UGA', _('Uganda')),
    ('UKR', _('Ukraine')),
    ('ARE', _('United Arab Emirates')),
    ('GBR', _('United Kingdom')),
    ('TZA', _('United Republic of Tanzania')),
    ('USA', _('United States of America')),
    ('VIR', _('United States Virgin Islands')),
    ('URY', _('Uruguay')),
    ('UZB', _('Uzbekistan')),
    ('VUT', _('Vanuatu')),
    ('VEN', _('Venezuela (Bolivarian Republic of)')),
    ('VNM', _('Viet Nam')),
    ('WLF', _('Wallis and Futuna Islands')),
    ('ESH', _('Western Sahara')),
    ('YEM', _('Yemen')),
    ('ZMB', _('Zambia')),
    ('ZWE', _('Zimbabwe')),
)

COUNTRY_DICT = {
    u'Afghanistan': 'AFG',
    u'Aland Islands': 'ALA',
    u'Albania': 'ALB',
    u'Algeria': 'DZA',
    u'American Samoa': 'ASM',
    u'Andorra': 'AND',
    u'Angola': 'AGO',
    u'Anguilla': 'AIA',
    u'Antarctica' : 'ATA',
    u'Antigua and Barbuda': 'ATG',
    u'Argentina': 'ARG',
    u'Armenia': 'ARM',
    u'Aruba': 'ABW',
    u'Australia': 'AUS',
    u'Austria': 'AUT',
    u'Azerbaijan': 'AZE',
    u'Bahamas': 'BHS',
    u'Bahrain': 'BHR',
    u'Bangladesh': 'BGD',
    u'Barbados': 'BRB',
    u'Belarus': 'BLR',
    u'Belgium': 'BEL',
    u'Belize': 'BLZ',
    u'Benin': 'BEN',
    u'Bermuda': 'BMU',
    u'Bhutan': 'BTN',
    u'Bolivia': 'BOL',
    u'Bosnia and Herzegovina': 'BIH',
    u'Botswana': 'BWA',
    u'Brazil': 'BRA',
    u'British Indian Ocean Territory': 'IOT',
    u'British Virgin Islands': 'VGB',
    u'Brunei Darussalam': 'BRN',
    u'Bulgaria': 'BGR',
    u'Burkina Faso': 'BFA',
    u'Burundi': 'BDI',
    u'Cambodia': 'KHM',
    u'Cameroon': 'CMR',
    u'Canada': 'CAN',
    u'Cape Verde': 'CPV',
    u'Cayman Islands': 'CYM',
    u'Central African Republic': 'CAF',
    u'Chad': 'TCD',
    u'Channel Islands': 'CIL',
    u'Chile': 'CHL',
    u'China': 'CHN',
    u'China - Hong Kong': 'HKG',
    u'China - Macao': 'MAC',
    u'Christmas Island': 'CXR',
    u'Cocos (Keeling) Islands': 'CCK',     
    u'Colombia': 'COL',
    u'Comoros': 'COM',
    u'Congo': 'COG',
    u'Cook Islands': 'COK',
    u'Costa Rica': 'CRI',
    u"Cote d'Ivoire": 'CIV',
    u"Cote D'Ivoire (Ivory Coast)" : 'CIV',
    u'Croatia': 'HRV',
    u'Cuba': 'CUB',
    u'Cyprus': 'CYP',
    u'Czech Republic': 'CZE',
    u"Democratic People's Republic of Korea": 'PRK',
    u'Democratic Republic of the Congo': 'COD',
    u'Denmark': 'DNK',
    u'Djibouti': 'DJI',
    u'Dominica': 'DMA',
    u'Dominican Republic': 'DOM',
    u'East Timor': 'TLS',
    u'Ecuador': 'ECU',
    u'Egypt': 'EGY',
    u'El Salvador': 'SLV',
    u'Equatorial Guinea': 'GNQ',
    u'Eritrea': 'ERI',
    u'Estonia': 'EST',
    u'Ethiopia': 'ETH',
    u'Faeroe Islands': 'FRO',
    u'Falkland Islands (Malvinas)': 'FLK',
    u'Faroe Islands': 'FRO',
    u'Federated States of Micronesia': 'FSM',
    u'Fiji': 'FJI',
    u'Finland': 'FIN',
    u'France': 'FRA',
    u'French Guiana': 'GUF',
    u'French Polynesia': 'PYF',
    u'French Southern Territories': 'ATF',
    u'Gabon': 'GAB',
    u'Gambia': 'GMB',
    u'Georgia': 'GEO',
    u'Germany': 'DEU',
    u'Ghana': 'GHA',
    u'Gibraltar': 'GIB',
    u'Greece': 'GRC',
    u'Greenland': 'GRL',
    u'Grenada': 'GRD',
    u'Guadeloupe': 'GLP',
    u'Guam': 'GUM',
    u'Guatemala': 'GTM',
    u'Guernsey': 'GGY',
    u'Guinea': 'GIN',
    u'Guinea-Bissau': 'GNB',
    u'Guyana': 'GUY',
    u'Haiti': 'HTI',
    u'Holy See (Vatican City)': 'VAT',
    u'Honduras': 'HND',
    u'Hong Kong': 'HKG',
    u'Hungary': 'HUN',
    u'Iceland': 'ISL',
    u'India': 'IND',
    u'Indonesia': 'IDN',
    u'Iran': 'IRN',
    u'Iraq': 'IRQ',
    u'Ireland': 'IRL',
    u'Isle of Man': 'IMN',
    u'Israel': 'ISR',
    u'Italy': 'ITA',
    u'Jamaica': 'JAM',
    u'Japan': 'JPN',
    u'Jersey': 'JEY',
    u'Jordan': 'JOR',
    u'Kazakhstan': 'KAZ',
    u'Kenya': 'KEN',
    u'Kiribati': 'KIR',
    u'Korea': 'KOR',
    u"Korea (North)": 'PRK',
    u'Kuwait': 'KWT',
    u'Kyrgyzstan': 'KGZ',
    u"Lao People's Democratic Republic": 'LAO',
    u"Laos": 'LAO',
    u'Latvia': 'LVA',
    u'Lebanon': 'LBN',
    u'Lesotho': 'LSO',
    u'Liberia': 'LBR',
    u'Libya': 'LBY',
    u'Libyan Arab Jamahiriya': 'LBY',
    u'Liechtenstein': 'LIE',
    u'Lithuania': 'LTU',
    u'Luxembourg': 'LUX',
    u'Macao': 'MAC',
    u'Macedonia': 'MKD',
    u'Madagascar': 'MDG',
    u'Malawi': 'MWI',
    u'Malaysia': 'MYS',
    u'Maldives': 'MDV',
    u'Mali': 'MLI',
    u'Malta': 'MLT',
    u'Marshall Islands': 'MHL',
    u'Martinique': 'MTQ',
    u'Mauritania': 'MRT',
    u'Mauritius': 'MUS',
    u'Mayotte': 'MYT',
    u'Mexico': 'MEX',
    u'Micronesia, Federated States of': 'FSM',
    u'Moldova': 'MDA',
    u'Monaco': 'MCO',
    u'Mongolia': 'MNG',
    u'Montenegro': 'MNE',
    u'Montserrat': 'MSR',
    u'Morocco': 'MAR',
    u'Mozambique': 'MOZ',
    u'Myanmar': 'MMR',
    u'Namibia': 'NAM',
    u'Nauru': 'NRU',
    u'Nepal': 'NPL',
    u'Netherlands': 'NLD',
    u'Netherlands Antilles': 'ANT',
    u'New Caledonia': 'NCL',
    u'New Zealand': 'NZL',
    u'Nicaragua': 'NIC',
    u'Niger': 'NER',
    u'Nigeria': 'NGA',
    u'Niue': 'NIU',
    u'Norfolk Island': 'NFK',
    u'Northern Mariana Islands': 'MNP',
    u'Norway': 'NOR',
    u'Occupied Palestinian Territory': 'PSE',
    u'Oman': 'OMN',
    u'Pakistan': 'PAK',
    u'Palau': 'PLW',
    u'Palestinian Territory': 'PSE',
    u'Panama': 'PAN',
    u'Papua New Guinea': 'PNG',
    u'Paraguay': 'PRY',
    u'Peru': 'PER',
    u'Philippines': 'PHL',
    u'Pitcairn': 'PCN',
    u'Poland': 'POL',
    u'Portugal': 'PRT',
    u'Puerto Rico': 'PRI',
    u'Qatar': 'QAT',
    u'Republic of Korea': 'KOR',
    u'Republic of Moldova': 'MDA',
    u'Reunion': 'REU',
    u'Romania': 'ROU',
    u'Russian Federation': 'RUS',
    u'Rwanda': 'RWA',
    u'Saint Helena': 'SHN',
    u'Saint Kitts and Nevis': 'KNA',
    u'Saint Lucia': 'LCA',
    u'Saint Pierre and Miquelon': 'SPM',
    u'Saint Vincent and the Grenadines': 'VCT',
    u'Saint-Barthelemy': 'BLM',
    u'Saint-Martin (French part)': 'MAF',
    u'Samoa': 'WSM',
    u'San Marino': 'SMR',
    u'Sao Tome and Principe': 'STP',
    u'Saudi Arabia': 'SAU',
    u'Senegal': 'SEN',
    u'Serbia': 'SRB',
    u'Seychelles': 'SYC',
    u'Sierra Leone': 'SLE',
    u'Singapore': 'SGP',
    u'Slovak Republic': 'SVK',
    u'Slovakia': 'SVK',
    u'Slovenia': 'SVN',
    u'Solomon Islands': 'SLB',
    u'Somalia': 'SOM',
    u'South Africa': 'ZAF',
    u'Spain': 'ESP',
    u'Sri Lanka': 'LKA',
    u'Sudan': 'SDN',
    u'Suriname': 'SUR',
    u'Svalbard and Jan Mayen': 'SJM',
    u'Svalbard and Jan Mayen Islands': 'SJM',
    u'Swaziland': 'SWZ',
    u'Sweden': 'SWE',
    u'Switzerland': 'CHE',
    u'Syria': 'SYR',
    u'Syrian Arab Republic': 'SYR',
    u'Tajikistan': 'TJK',
    u'Tanzania' : 'TZA',
    u'Taiwan' : 'TWN',
    u'Thailand': 'THA',
    u'Timor-Leste': 'TLS',
    u'Togo': 'TGO',
    u'Tokelau': 'TKL',
    u'Tonga': 'TON',
    u'Trinidad and Tobago': 'TTO',
    u'Tunisia': 'TUN',
    u'Turkey': 'TUR',
    u'Turkmenistan': 'TKM',
    u'Turks and Caicos Islands': 'TCA',
    u'Tuvalu': 'TUV',
    u'Uganda': 'UGA',
    u'Ukraine': 'UKR',
    u'United Arab Emirates': 'ARE',
    u'United Kingdom': 'GBR',
    u'United Republic of Tanzania': 'TZA',
    u'United States Virgin Islands': 'VIR',
    u'United States': 'USA',
    u'United States of America': 'USA',
    u'Uruguay': 'URY',
    u'Uzbekistan': 'UZB',
    u'Vanuatu': 'VUT',
    u'Vatican City State (Holy See)': 'VAT',
    u'Venezuela': 'VEN',
    u'Venezuela (Bolivarian Republic of)': 'VEN',
    u'Viet Nam': 'VNM',
    u'Vietnam': 'VNM',
    u'Virgin Islands (British)': 'VGB',
    u'Virgin Islands (U.S.)': 'VIR',
    u'Wallis and Futuna': 'WLF',
    u'Wallis and Futuna Islands': 'WLF',
    u'Western Sahara': 'ESH',
    u'Yemen': 'YEM',
    u'Zambia': 'ZMB',
    u'Zimbabwe': 'ZWE'
}

class CountryField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('max_length', 3)
        kwargs.setdefault('choices', COUNTRIES)

        super(CountryField, self).__init__(*args, **kwargs)

    def get_internal_type(self):
        return "CharField"