from django_backend_tests import *
from drug_searcher_tests import *
from exchange_tests import *
from formulation_page_tests import *
from formulation_table_tests import *
from formulation_graph_tests import *
from incoterm_tests import *
from media_tests import *
from menu_tests import *
from price_tests import *
from product_page_tests import *
from product_registration_tests import *
from product_table_tests import *
from results_table_tests import *
from sarpam_table_tests import *
from search_form_tests import *
from search_tests import *
from supplier_catalogue_page_tests import *
from template_tests import *
from utils_tests import *
