# pylint: disable-msg=W0401
from sarpaminfohub.infohub.tests.django_backend_tests import *
from sarpaminfohub.infohub.tests.drug_searcher_tests import *
from sarpaminfohub.infohub.tests.exchange_tests import *
from sarpaminfohub.infohub.tests.formulation_page_tests import *
from sarpaminfohub.infohub.tests.formulation_table_tests import *
from sarpaminfohub.infohub.tests.formulation_graph_tests import *
from sarpaminfohub.infohub.tests.formulation_product_page_tests import *
from sarpaminfohub.infohub.tests.incoterm_tests import *
from sarpaminfohub.infohub.tests.media_tests import *
from sarpaminfohub.infohub.tests.menu_tests import *
from sarpaminfohub.infohub.tests.price_popup_tests import *
from sarpaminfohub.infohub.tests.price_tests import *
from sarpaminfohub.infohub.tests.product_page_tests import *
from sarpaminfohub.infohub.tests.product_registration_tests import *
from sarpaminfohub.infohub.tests.product_table_tests import *
from sarpaminfohub.infohub.tests.product_tests import *
from sarpaminfohub.infohub.tests.results_table_tests import *
from sarpaminfohub.infohub.tests.sarpam_table_tests import *
from sarpaminfohub.infohub.tests.search_form_tests import *
from sarpaminfohub.infohub.tests.search_tests import *
from sarpaminfohub.infohub.tests.supplier_catalogue_page_tests import *
from sarpaminfohub.infohub.tests.template_tests import *
from sarpaminfohub.infohub.tests.utils_tests import *
